/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

/**
 *
 * @author lmcdo
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Start_Button = new javax.swing.JButton();
        Deck_Button = new javax.swing.JButton();
        Options_Button = new javax.swing.JButton();
        Help_Button = new javax.swing.JButton();
        Exit_Button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Main Menu");
        Menu.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 260, 69));

        Start_Button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Start_Button.setText("START");
        Menu.add(Start_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 320, 60));

        Deck_Button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Deck_Button.setText("Deck Builder");
        Menu.add(Deck_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 320, 50));

        Options_Button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Options_Button.setText("Options");
        Menu.add(Options_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 320, 50));

        Help_Button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Help_Button.setText("Help");
        Menu.add(Help_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 320, 50));

        Exit_Button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Exit_Button.setText("EXIT");
        Menu.add(Exit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 320, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/MainMenu_Background.jpg"))); // NOI18N
        Menu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deck_Button;
    private javax.swing.JButton Exit_Button;
    private javax.swing.JButton Help_Button;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton Options_Button;
    private javax.swing.JButton Start_Button;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
