/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/*
2 formats possible for communication
Either use stop and wait for info to pass between
Or set class data info such as Database.defdeck1 = df1;
*/
package game.SCREENS;
import game.*;
/**
 *
 * @author lmcdo
 */
public class SCREEN_Decks extends javax.swing.JFrame {

    private static Deck df1,df2,df3,df4,df5,cs1,cs2,cs3,cs4,cs5;
    /**
     * Creates new form Decks
     */
    public SCREEN_Decks(Deck d1, Deck d2, Deck d3, Deck d4, Deck d5, Deck c1, Deck c2, Deck c3, Deck c4, Deck c5) {
        initComponents();
        this.df1 = d1;this.df2 = d2;this.df3 = d3;this.df4 = d4;this.df5 = d5;
        //add IF csi.equals(null)
        this.cs1 = c1;this.cs2 = c2;this.cs3 = c3;this.cs4 = c4; this.cs5 = c5;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Text_1 = new javax.swing.JLabel();
        Create_Button = new javax.swing.JButton();
        Edit_Button = new javax.swing.JButton();
        Delete_Button = new javax.swing.JButton();
        Return_Button = new javax.swing.JButton();
        Deck_Tab = new javax.swing.JTabbedPane();
        Custom_Tab = new javax.swing.JScrollPane();
        Custom_List = new javax.swing.JList<>();
        Default_Tab = new javax.swing.JScrollPane();
        Default_List = new javax.swing.JList<>();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("       Deck ");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 220, 69));

        Text_1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Text_1.setForeground(new java.awt.Color(51, 51, 51));
        Text_1.setText("Select a Deck");
        jPanel1.add(Text_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 170, 40));

        Create_Button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Create_Button.setText("Create New");
        Create_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Create_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 140, 50));

        Edit_Button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Edit_Button.setText("Edit ");
        Edit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Edit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 140, 40));

        Delete_Button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Delete_Button.setText("Delete");
        Delete_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Delete_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 140, 40));

        Return_Button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Return_Button.setText("Return");
        Return_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return_ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Return_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        Custom_List.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Custom_List.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        Custom_List.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Deck 1", "Deck 2", "Deck 3", "Deck 4", "Deck 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Custom_List.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        Custom_Tab.setViewportView(Custom_List);

        Deck_Tab.addTab("tab1", Custom_Tab);

        Default_List.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Default_List.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        Default_List.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Default 1", "Default 2", "Default 3", "Default 4", "Default 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Default_List.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        Default_Tab.setViewportView(Default_List);

        Deck_Tab.addTab("tab2", Default_Tab);

        jPanel1.add(Deck_Tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 270, 360));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/FantasyTabletop_1.jpg"))); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Create_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_ButtonActionPerformed
        // TODO add your handling code here:
        SCREEN_DeckView dv = new SCREEN_DeckView();
        dv.setVisible(true);
        dispose();
    }//GEN-LAST:event_Create_ButtonActionPerformed

    private void Return_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return_ButtonActionPerformed
        // TODO add your handling code here:
        SCREEN_MainMenu mm = new SCREEN_MainMenu();
        mm.setVisible(true);
        dispose();
    }//GEN-LAST:event_Return_ButtonActionPerformed

    private void Edit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_ButtonActionPerformed
        // TODO add your handling code here:
        //selectedDeck.edit()
        selectedItem = Custom_List.getSelectedValue();
        SCREEN_DeckView dv = new SCREEN_DeckView();
        dv.setVisible(true);
        dispose();
    }//GEN-LAST:event_Edit_ButtonActionPerformed

    private void Delete_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_ButtonActionPerformed
        // TODO add your handling code here:
        //selectedDeck.remove()
        SCREEN_DeckView dv = new SCREEN_DeckView();
        dv.setVisible(true);
        dispose();
    }//GEN-LAST:event_Delete_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SCREEN_Decks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SCREEN_Decks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SCREEN_Decks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SCREEN_Decks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SCREEN_Decks(df1, df2, df3, df4, df5, cs1, cs2, cs3, cs4, cs5).setVisible(true);
            }
        });
    }
    public static String selectedItem;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Create_Button;
    private javax.swing.JList<String> Custom_List;
    private javax.swing.JScrollPane Custom_Tab;
    private javax.swing.JTabbedPane Deck_Tab;
    private javax.swing.JList<String> Default_List;
    private javax.swing.JScrollPane Default_Tab;
    private javax.swing.JButton Delete_Button;
    private javax.swing.JButton Edit_Button;
    private javax.swing.JButton Return_Button;
    private javax.swing.JLabel Text_1;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
